export {default as OpenSection} from './OpenSection'
export {default as About} from './About'
export { default as Projects} from './Projects'
export { default as Tools} from './Tools'
export {default as Footer} from './Footer'
export {default as Copyright} from './Copyright'